-- INSERT PROVINCIAS

insert into provincia (nombre, codprov) values ('ALAVA', '01');
insert into provincia (nombre, codprov) values ('ALBACETE', '02');
insert into provincia (nombre, codprov) values ('ALICANTE', '03');
insert into provincia (nombre, codprov) values ('ALMERIA', '04');
insert into provincia (nombre, codprov) values ('AVILA', '05');
insert into provincia (nombre, codprov) values ('BADAJOZ', '06');
insert into provincia (nombre, codprov) values ('ISLAS BALEARES', '07');
insert into provincia (nombre, codprov) values ('BARCELONA', '08');
insert into provincia (nombre, codprov) values ('BURGOS', '09');
insert into provincia (nombre, codprov) values ('CACERES', '10');
insert into provincia (nombre, codprov) values ('CADIZ', '11');
insert into provincia (nombre, codprov) values ('CASTELLON', '12');
insert into provincia (nombre, codprov) values ('CIUDAD REAL', '13');
insert into provincia (nombre, codprov) values ('CORDOBA', '14');
insert into provincia (nombre, codprov) values ('LA CORUÑA', '15');
insert into provincia (nombre, codprov) values ('CUENCA', '16');
insert into provincia (nombre, codprov) values ('GERONA', '17');
insert into provincia (nombre, codprov) values ('GRANADA', '18');
insert into provincia (nombre, codprov) values ('GUADALAJARA', '19');
insert into provincia (nombre, codprov) values ('GUIPUZCOA', '20');
insert into provincia (nombre, codprov) values ('HUELVA', '21');
insert into provincia (nombre, codprov) values ('HUESCA', '22');
insert into provincia (nombre, codprov) values ('JAEN', '23');
insert into provincia (nombre, codprov) values ('LEON', '24');
insert into provincia (nombre, codprov) values ('LERIDA', '25');
insert into provincia (nombre, codprov) values ('LA RIOJA', '26');
insert into provincia (nombre, codprov) values ('LUGO', '27');
insert into provincia (nombre, codprov) values ('MADRID', '28');
insert into provincia (nombre, codprov) values ('MALAGA', '29');
insert into provincia (nombre, codprov) values ('MURCIA', '30');
insert into provincia (nombre, codprov) values ('NAVARRA', '31');
insert into provincia (nombre, codprov) values ('OURENSE', '32');
insert into provincia (nombre, codprov) values ('ASTURIAS', '33');
insert into provincia (nombre, codprov) values ('PALENCIA', '34');
insert into provincia (nombre, codprov) values ('LAS PALMAS', '35');
insert into provincia (nombre, codprov) values ('PONTEVEDRA', '36');
insert into provincia (nombre, codprov) values ('SALAMANCA', '37');
insert into provincia (nombre, codprov) values ('SANTA CRUZ DE TENERIFE', '38');
insert into provincia (nombre, codprov) values ('CANTABRIA', '39');
insert into provincia (nombre, codprov) values ('SEGOVIA', '40');
insert into provincia (nombre, codprov) values ('SEVILLA', '41');
insert into provincia (nombre, codprov) values ('SORIA', '42');
insert into provincia (nombre, codprov) values ('TARRAGONA', '43');
insert into provincia (nombre, codprov) values ('TERUEL', '44');
insert into provincia (nombre, codprov) values ('TOLEDO', '45');
insert into provincia (nombre, codprov) values ('VALENCIA', '46');
insert into provincia (nombre, codprov) values ('VALLADOLID', '47');
insert into provincia (nombre, codprov) values ('VIZCAYA', '48');
insert into provincia (nombre, codprov) values ('ZAMORA', '49');
insert into provincia (nombre, codprov) values ('ZARAGOZA', '50');
insert into provincia (nombre, codprov) values ('CEUTA', '51');
insert into provincia (nombre, codprov) values ('MELILLA', '52');
