INSERT INTO mykebab.kebab (nombre, foto, precio, descripcion, estado) VALUES
('Kebab Al Gusto', 'kebab_al_gusto.jpg', 7.00, 'Kebab al gusto del consumidor con 3 ingredientes incluidos y extras disponibles', 'activo'),
('Kebab Clásico Pollo', 'kebab_clasico_Pollo.jpg', 5.00, 'Kebab con pan de pita y carne de pollo', 'activo'),
('Kebab Clásico Ternera', 'kebab_clasico_Ternera.jpg', 5.00, 'Kebab con pan de pita y carne de ternera', 'activo'),
('Kebab Clásico Cordero', 'kebab_clasico_Cordero.jpg', 5.00, 'Kebab con pan de pita y carne de cordero', 'activo'),
('Kebab Clásico Falafel', 'kebab_clasico_Falafel.jpg', 5.00, 'Kebab con pan de pita y carne de falafel', 'activo'),
('Kebab Libanes Pollo', 'kebab_Libanes_Pollo.jpg', 5.00, 'Kebab con pan libanés y carne de pollo', 'activo'),
('Kebab Libanes Ternera', 'kebab_Libanes_Ternera.jpg', 5.00, 'Kebab con pan libanés y carne de ternera', 'activo'),
('Kebab Libanes Cordero', 'kebab_Libanes_Cordero.jpg', 5.00, 'Kebab con pan libanés y carne de cordero', 'activo'),
('Kebab Libanes Falafel', 'kebab_Libanes_Falafel.jpg', 5.00, 'Kebab con pan libanés y carne de falafel', 'activo'),
('Kebab Especial Pollo', 'kebab_especial_pollo.jpg', 6.50, 'Kebab con pan libanés, carne de pollo y vegetales', 'activo'),
('Kebab Especial Ternera', 'kebab_especial_ternera.jpg', 6.50, 'Kebab con pan libanés, carne de ternera y vegetales', 'activo'),
('Kebab Especial Cordero', 'kebab_especial_cordero.jpg', 6.50, 'Kebab con pan libanés, carne de cordero y vegetales', 'activo'),
('Kebab Especial Falafel', 'kebab_especial_falafel.jpg', 6.50, 'Kebab con pan libanés, falafel y vegetales', 'activo'),
('Kebab Super Vegetal', 'kebab_Super_vegetal.jpg', 7.00, 'Kebab con pan de pita, falafel y extra de vegetales', 'activo'),
('Kebab Super Pollo y Ternera', 'Kebab_Super_Pollo_ternera.jpg', 7.00, 'Kebab mixto con tortilla de trigo, carne de pollo y ternera', 'activo'),
('Kebab Super Ternera y Cordero', 'Kebab_Super_Ternera_Cordero.jpg', 7.00, 'Kebab mixto con tortilla de trigo, carne de ternera y cordero', 'activo'),
('Kebab Super Cordero y Pollo', 'Kebab_Super_Cordero_Pollo.jpg', 7.00, 'Kebab mixto con tortilla de trigo, carne de cordero y pollo', 'activo');
