INSERT INTO alergenos (nombre, imagen) VALUES
('Gluten', 'gluten.jpg'),
('Crustáceos', 'crustaceos.jpg'),
('Huevos', 'huevos.jpg'),
('Pescado', 'pescado.jpg'),
('Cacahuetes', 'cacahuetes.jpg'),
('Soja', 'soja.jpg'),
('Lácteos', 'lacteos.jpg'),
('Frutos de Cáscara', 'frutos_de_cascara.jpg'),
('Apio', 'apio.jpg'),
('Mostaza', 'mostaza.jpg'),
('Sésamo', 'sesamo.jpg'),
('Sulfitos', 'sulfitos.jpg'),
('Altramuces', 'altramuces.jpg'),
('Moluscos', 'moluscos.jpg');
